lets_travel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lets_travel_app.urls')),
    path('admin/', admin.site.urls),
]

lets_travel_app/urls.py
from django.urls import path
from . import views

app_name = 'lets_travel_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.registration, name='registration'),
    path('registration_process/', views.registration_process, name='registration_process'),
    path('login/', views.login_form, name='login'),
    path('login_process/', views.login_process, name='login_process'),
    path('logout_process/', views.logout_process, name='logout_process'),
    path('user_profile/<username>/', views.user_profile, name='user_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('edit_profile_process/', views.edit_profile_process, name='edit_profile_process'),
    path('visited_places/<username>/', views.visited_places, name='visited_places'),
    path('visited_place/', views.visited_place, name='visited_place'),
    path('visited_place_form/', views.visited_place_form, name='visited_place_form'),
    path('delete_visited_place/', views.delete_visited_place, name='delete_visited_place'),
    path('visited_place_process/', views.visited_place_process, name='visited_place_process'),
    path('wish_list/<username>/', views.wish_list, name='wish_list'),
    path('wish_place/', views.wish_place, name='wish_place'),
    path('wish_place_form/', views.wish_place_form, name='wish_place_form'),
    path('delete_wish_place/', views.delete_wish_place, name='delete_wish_place'),
    path('wish_place_process/', views.wish_place_process, name='wish_place_process'),
    path('articles/', views.articles, name='articles'),
    path('article/', views.article, name='article'),
    path('countries/', views.countries, name='countries'),
    path('country/', views.country, name='country'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('error_404', views.error_404, name='error_404'),

    path('ajax/increment_likes_article/', views.increment_likes_article, name='increment_likes_article'),
    path('ajax/add_comment_article/', views.add_comment_article, name='add_comment_article'),
    path('ajax/delete_comment_article/', views.delete_comment_article, name='delete_comment_article'),
    path('ajax/edit_comment_article/', views.edit_comment_article, name='edit_comment_article'),
    path('ajax/increment_likes_visited_place/', views.increment_likes_visited_place, name='increment_likes_visited_place'),
    path('ajax/add_comment_visited_place/', views.add_comment_visited_place, name='add_comment_visited_place'),
    path('ajax/delete_comment_visited_place/', views.delete_comment_visited_place, name='delete_comment_visited_place'),
    path('ajax/edit_comment_visited_place/', views.edit_comment_visited_place, name='edit_comment_visited_place'),
    path('ajax/increment_likes_wish_place/', views.increment_likes_wish_place,name='increment_likes_wish_place'),
    path('ajax/add_comment_wish_place/', views.add_comment_wish_place, name='add_comment_wish_place'),
    path('ajax/delete_comment_wish_place/', views.delete_comment_wish_place, name='delete_comment_wish_place'),
    path('ajax/edit_comment_wish_place/', views.edit_comment_wish_place, name='edit_comment_wish_place'),
    path('ajax/cities_for_visited_place/', views.cities_for_visited_place, name='cities_for_visited_place'),
    path('ajax/cities_for_wish_place/', views.cities_for_wish_place, name='cities_for_wish_place'),
]

templates/lets_travel_app_templates/articles.html
{% extends "lets_travel_app_templates/base.html" %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}

    <div class="content_blocks">
        <h4 class="content_captions_on_main">Articles</h4>
        <div class="block_content_all_items">
            {% for article in articles %}
                <div class="block_each_item">
                    <div><img src="{{ article.image }}"></div>
                    <a href="{% url 'lets_travel_app:article' %}?id={{ article.id }}"><div class="caption_h50px">{{ article.caption }}</div></a>
                    <div class="blocks_teaser">{{ article.teaser }}</div>
                    <div class="comments_and_likes_amount">
                        <div  id="comments_amount">
                            {{ article.comments.count }} Comment{{ article.comments.count|pluralize }}
                        </div>
                        <div id="likes_amount">
                            {{ article.likes.count }} Like{{ article.likes.count|pluralize }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/lets_travel_app_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Let's travel!{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'external/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/webfontkit-20180131-112835/stylesheet.css' %}">
</head>
<body>

    <div class="container-fluid">

        <div class="header">
            <div class="header_user_info_block ml-2">
                {% if user.is_authenticated %}
                    <div class="user_image_30px_round">
                        {% if user.photo %}
                            <a href="{% url 'lets_travel_app:user_profile' user.username %}"><img src="{{ user.photo }}"></a>
                        {% else %}
                            <a href="{% url 'lets_travel_app:user_profile' user.username %}"><img src="{% static 'pictures/no_user_photo.png' %}"></a>
                        {% endif %}
                    </div>
                    <div class="user_links_block">
                        Hello, <a href="{% url 'lets_travel_app:user_profile' user.username %}">{{ user.username }}</a>
                        <a class="ml-3" href="{% url 'lets_travel_app:logout_process' %}">Log Out</a>
                    </div>
                {% else %}
                    <a href="{% url 'lets_travel_app:registration' %}">Registration</a>
                    <a class="ml-3" href="{% url 'lets_travel_app:login' %}">Log In</a>
                {% endif %}
            </div>

            <a href="{% url 'lets_travel_app:index' %}"><div class="title">Let's travel!</div></a>


            <div class="header_links_block mr-2">
                <a href="{% url 'lets_travel_app:index' %}">Home</a>
                <a class="ml-2" href="{% url 'lets_travel_app:contact_us' %}">Contact us</a>
            </div>
        </div>


        <div class="main">
            {% block content %}
            {% endblock %}
        </div>

    </div>

    <script src="{% static 'external/bootstrap/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'external/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'external/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/global.js' %}"></script>

</body>

    {% block external_scripts %}{% endblock %}

</html>

templates/lets_travel_app_templates/index.html
{% extends "lets_travel_app_templates/base.html" %}
{% load static %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}

    <div class="homepage_img">
        <img src="{% static 'pictures/Bali-Temple-Banner.jpg' %}">
    </div>
    <div class="content_blocks">
        <a href="{% url 'lets_travel_app:articles' %}"><h4 class="content_captions_on_main">Articles</h4></a>
        <div class="block_content_on_main">
            {% for article in articles_on_homepage %}
                <div class="blocks_on_main">
                    <div><img src="{{ article.image }}"></div>
                    <a href="{% url 'lets_travel_app:article' %}?id={{ article.id }}"><div class="caption_articles_on_main">{{ article.caption }}</div></a>
                    <div class="blocks_teaser">{{ article.teaser }}</div>
                    <div class="comments_and_likes_amount">
                        <div  id="comments_amount">
                            {{ article.comments.count }} Comment{{ article.comments.count|pluralize }}
                        </div>
                        <div id="likes_amount">
                            {{ article.likes.count }} Like{{ article.likes.count|pluralize }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="content_blocks">
        <a href="{% url 'lets_travel_app:countries' %}"><h4 class="content_captions_on_main">Countries</h4></a>
        <div class="block_content_on_main">
            {% for country in countries_on_homepage %}
                <div class="blocks_on_main">
                    <div><img src="{{ country.image }}"></div>
                    <a href="{% url 'lets_travel_app:country' %}?id={{ country.id }}"><div class="caption_h50px">{{ country.caption }}</div></a>
                    <div class="blocks_teaser">{{ country.teaser }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="content_blocks">
        <div class="flex_space_between_main">
            <div class="places_caption_on_main">
                <a href="{% url 'lets_travel_app:countries' %}"><h4 class="content_captions_on_main">Visited places</h4></a>
            </div>
            <div class="places_caption_on_main">
                <a href="{% url 'lets_travel_app:countries' %}"><h4 class="content_captions_on_main">Dreams about...</h4></a>
            </div>
        </div>
        <div class="flex_space_between_main">
            <div class="places_on_main">
                {% for visited_place in visited_places_on_homepage %}
                    <div class="place_on_main">
                        <div class="user_img_60px_round">
                            {% if visited_place.author.photo %}
                                <a href="{% url 'lets_travel_app:user_profile' visited_place.author.username %}"><img src="{{ visited_place.author.photo }}"></a>
                            {% else %}
                                <a href="{% url 'lets_travel_app:user_profile' visited_place.author.username %}"><img src="{% static 'pictures/no_user_photo.png' %}"></a>
                            {% endif %}
                        </div>
                        <div class="place_info_on_main">
                            <a href="{% url 'lets_travel_app:user_profile' visited_place.author.username %}">{{ visited_place.author.username }}</a> was in {{ visited_place.country }}<br>
                            <div class="text_0_8em">from {{ visited_place.start_date|date:"j F Y" }} till {{ visited_place.end_date|date:"j F Y" }}</div>
                            <div class="text_0_8em"><a href="{% url 'lets_travel_app:visited_place' %}?id={{ visited_place.id }}">View details</a></div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="places_on_main">
                {% for wish_place in wish_places_on_homepage %}
                    <div class="place_on_main">
                        <div class="user_img_60px_round">
                            {% if wish_place.author.photo %}
                                <a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}"><img src="{{ wish_place.author.photo }}"></a>
                            {% else %}
                                <a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}"><img src="{% static 'pictures/no_user_photo.png' %}"></a>
                            {% endif %}
                        </div>
                        <div class="place_info_on_main">
                            <a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}">{{ wish_place.author.username }}</a> wants to visit {{ wish_place.country }}
                            <div class="text_0_8em"><a href="{% url 'lets_travel_app:wish_place' %}?id={{ wish_place.id }}">View details</a></div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

{% block external_scripts %}

    <script>

    </script>

{% endblock %}

templates/lets_travel_app_templates/user_profile.html
{% extends "lets_travel_app_templates/base.html" %}
{% load static %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}

    {% if profile_owner %}
        <h4>Hello, {{ user_profile.username }}</h4>
        <div class="user_profile_container">
            <div class="profile_picture">
                {% if user_profile.photo %}
                    <img src="{{ user_profile.photo }}">
                {% else %}
                    <img src="{% static 'pictures/no_user_photo.png' %}">
                {% endif %}
            </div>
            <div class="user_details_container">
                <div class="user_details">
                    {% if user_profile.get_full_name %}
                        <h5>{{ user_profile.get_full_name }}</h5>
                    {% endif %}
                    {% if user_profile.birthday %}
                        {{ user_profile.birthday }}
                    {% endif %}<br>
                    <a href="{% url 'lets_travel_app:edit_profile' %}">Edit profile</a>
                </div>
                <div>
                    <a class="mr-2" href="{% url 'lets_travel_app:visited_places' user_profile.username %}">Visited places</a>
                    <a class="mr-2" href="{% url 'lets_travel_app:wish_list' user_profile.username %}">Wish list</a>
                </div>
            </div>
            <div class="about_user">
                {{ user_profile.information }}
            </div>
        </div>
    {% elif authorized_guest %}
        <h4>{{ user_profile.username }}</h4>
        <div class="user_profile_container">
            <div class="profile_picture">
                {% if user_profile.photo %}
                    <img src="{{ user_profile.photo }}">
                {% else %}
                    <img src="{% static 'pictures/no_user_photo.png' %}">
                {% endif %}
            </div>
            <div class="user_details_container">
                <div class="user_details">
                    {% if user_profile.get_full_name %}
                        <h5>{{ user_profile.get_full_name }}</h5>
                    {% endif %}
                    {% if user_profile.birthday %}
                        {{ user_profile.birthday }}
                    {% endif %}<br>
                </div>
                <div>
                    <a class="mr-2" href="{% url 'lets_travel_app:visited_places' user_profile.username %}">Visited places</a>
                    <a class="mr-2" href="{% url 'lets_travel_app:wish_list' user_profile.username %}">Wish list</a>
                </div>
            </div>
            <div class="about_user">
                {{ user_profile.information }}
            </div>
        </div>
    {% else %}
        <a href="{% url 'lets_travel_app:registration' %}">Registration</a><br>
        <a href="{% url 'lets_travel_app:login' %}">Log In</a><br><br>
    {% endif %}

{% endblock %}

templates/lets_travel_app_templates/wish_list.html
{% extends "lets_travel_app_templates/base.html" %}
{% load static %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}

    <div class="content_blocks">
        <h4 class="content_captions_on_main">Wish list</h4>
        <div class="block_content_all_items">
            {% for wish_place in  wish_list %}
                <div class="blocks_each_place">
                    <div class="place_info">
                        <div>
                            <div class="edit_and_del_btns text_0_8em mt-1">
                                {% if profile_owner %}
                                    <div class="mr-1"><a href="{% url 'lets_travel_app:wish_place_form' %}?id={{ wish_place.id }}"><span>Edit</span><img src="{% static 'pictures/edit_icon.png' %}"></a></div>
                                    <form action="{% url 'lets_travel_app:delete_wish_place' %}" method="POST">{% csrf_token %}
                                        <div onclick="var $delete_place = $(this).parent(); process_confirm('Delete place?', function(){$delete_place.submit()}); return false;"><span>Delete</span><img src="{% static 'pictures/delete_icon.png' %}"></div>
                                        <input type="hidden" name="id" value="{{ wish_place.id }}">
                                    </form>
                                {% endif %}
                            </div>
                            <div class="text_1_2em_bold caption_places_block">
                                <a href="{% url 'lets_travel_app:wish_place' %}?id={{ wish_place.id }}">{{ wish_place.country }}</a>
                            </div>
                        </div>
                        <div class="text_0_9em mb-1">{{ wish_place.all_cities }}</div>
                        <div class="text_0_8em">created on {{ wish_place.created_date }}</div>
                    </div>
                    <div>
                        <div class="text_0_9em comments_and_likes_amount mb-0">
                            <div  id="comments_amount">
                                {{ wish_place.comments.count }} Comment{{ wish_place.comments.count|pluralize }}
                            </div>
                            <div id="likes_amount">
                                {{ wish_place.likes.count }} Like{{ wish_place.likes.count|pluralize }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if profile_owner %}
                <div class="icon"><a href="{% url 'lets_travel_app:wish_place_form' %}">Add new place<img src="{% static 'pictures/add_icon.png' %}"></a></div>
        {% endif %}
    </div>

{% endblock %}

templates/lets_travel_app_templates/wish_place.html
{% extends "lets_travel_app_templates/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}

    <div class="container_content_width800px">
        <div class="place">
            <div id="wish_place_id" style="display: none;">{{ wish_place.id }}</div>
            <div class="place_user">
                <div class="user_img_60px_round">
                    {% if wish_place.author.photo %}
                        <a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}"><img src="{{ wish_place.author.photo }}"></a>
                    {% else %}
                        <a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}"><img src="{% static 'pictures/no_user_photo.png' %}"></a>
                    {% endif %}
                </div>
                <div class="font-weight-bold"><a href="{% url 'lets_travel_app:user_profile' wish_place.author.username %}">{{ wish_place.author.username }}</a></div>
            </div>
            <div class="place_details">
                <div class="text_1_2em_bold">{{ wish_place.country }}</div>
                <div class="text_0_9em">{{ wish_place.all_cities }}</div>
                <div class="text_0_8em">created on {{ wish_place.created_date }}</div>
                <div>{{ wish_place.description }}</div>
            </div>
            <div class="edit_and_del_btns">
                {% if profile_owner %}
                    <div class="mr-2"><a href="{% url 'lets_travel_app:wish_place_form' %}?id={{ wish_place.id }}"><span>Edit</span><img src="{% static 'pictures/edit_icon.png' %}"></a></div>
                    <form action="{% url 'lets_travel_app:delete_wish_place' %}" id="delete_form" method="POST">{% csrf_token %}
                        <div onclick="var $delete_place = $(this).parent(); process_confirm('Delete place?', function(){$delete_place.submit()}); return false;"><span>Delete</span><img src="{% static 'pictures/delete_icon.png' %}"></div>
                        <input type="hidden" name="id" value="{{ wish_place.id }}">
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="comments_and_likes_amount">
            <div  id="comments_amount">
                {{ wish_place.comments.count }} Comment{{ wish_place.comments.count|pluralize }}
            </div>
            {% if request.user.is_authenticated %}
                <div id="likes">
                    {% if is_liked %}
                        <div class="like d-flex align-items-center" id="like_button">
                            <div id="like_status">
                                <img src="{% static 'pictures/heart_like_icon.png' %}">Liked
                            </div>
                        </div>
                    {% else %}
                        <div class="like d-flex align-items-center" id="like_button">
                            <div id="like_status">
                                <img src="{% static 'pictures/like_icon.png' %}">Like
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
            <div id="likes_amount">
                {{ wish_place.likes.count }} Like{{ wish_place.likes.count|pluralize }}
            </div>
        </div>
        <div class="comments" id="added_comments">
            {% for comment in wish_place.comments.all %}
                <div class="comment">
                    <div class="user_img_60px_round">
                        {% if comment.author.photo %}
                            <a href="{% url 'lets_travel_app:user_profile' comment.author.username %}"><img src="{{ comment.author.photo }}"></a>
                        {% else %}
                            <a href="{% url 'lets_travel_app:user_profile' comment.author.username %}"><img src="{% static 'pictures/no_user_photo.png' %}"></a>
                        {% endif %}
                    </div>
                    <div class="comment_details">
                        {% if request.user == comment.author %}
                            <div class="edit_and_del_btns">
                                <div class="edit_comment_button mr-2"><span>Edit</span><img src="{% static 'pictures/edit_icon.png' %}"></div>
                                <div class="delete_comment_button"><span>Delete</span><img src="{% static 'pictures/delete_icon.png' %}"></div>
                            </div>
                        {% endif %}
                        <div class="font-weight-bold"><a href="{% url 'lets_travel_app:user_profile' comment.author.username %}">{{ comment.author.username }}</a></div>
                        <div class="mb-2 exist_text">{{ comment.text }}</div>
                        <div class="text_0_8em">{{ comment.date|date:"d-m-Y H:i" }}</div>
                        <div class="edit_container form-group" style="display: none;">
                            <label for="textarea"></label>
                            <textarea class="edit_text form-control" id="textarea"></textarea><br/>
                            <input type="submit" class="save_edited_comment form-control btn btn-primary mr-2" value="Save"/>
                            <input type="submit" class="cancel_edit_comment form-control btn btn-primary" value="Cancel"/>
                        </div>
                        <div class="comment_id" style="display: none;">{{ comment.id }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
            <div class="add_comment">
                <div class="form-group">
                    <label for="text"></label>
                    <textarea class="form-control" name="text" id="comment_text" rows="5" placeholder="Write a comment"></textarea>
                </div>
                <div class="form-group add_com_button">
                    <input class="form-control btn btn-primary" type="submit" value="Add comment" id="add_comment_button">
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block external_scripts %}

    <script>

        $("#like_button").on("click", function () {
            var wish_place_id = $("#wish_place_id").text();
            $.post({
                url:'{% url "lets_travel_app:increment_likes_wish_place" %}',
                data:{"wish_place_id": wish_place_id},
                success:function (response) {
                    if (response.success){
                        var like_amount = response.amount_of_likes;
                        var like_status = response.like_change;
                        if (like_status === "Liked"){
                            $("#like_status").html('<img src="{% static 'pictures/heart_like_icon.png' %}">' + like_status);
                        }else{
                            $("#like_status").html('<img src="{% static 'pictures/like_icon.png' %}">' + like_status);

                        }
                        if (like_amount ===  0 || like_amount >= 2){
                            $("#likes_amount").text(like_amount + ' Likes');
                        }else{
                            $("#likes_amount").text(like_amount + ' Like');
                        }
                    }else{
                        alert("error");
                    }
                }
            })
        });


        $("#add_comment_button").on("click", function(){
            var wish_place_id = $("#wish_place_id").text();
            var $comment_text_area = $("#comment_text");
            var text = $comment_text_area.val();
            $.post({
                url:'{% url "lets_travel_app:add_comment_wish_place" %}',
                data:{"wish_place_id": wish_place_id, "text": text},
                success:function (response) {
                    if (response.success){
                        var html = response.html_str;
                        var $added_comments = $("#added_comments");
                        $added_comments.html($added_comments.html() + html);
                        var comments_amount = response.amount_of_comments;
                        if (comments_amount ===  0 || comments_amount >= 2){
                            $("#comments_amount").text(comments_amount + ' Comments');
                        }else{
                            $("#comments_amount").text(comments_amount + ' Comment');
                        }
                        $comment_text_area.val("");
                        init_buttons();
                    }else{
                        alert("error");
                    }
                }

            })
        });


        function init_buttons() {
            $(".delete_comment_button").on("click", function () {
                var $delete_btn = $(this);
                process_confirm("Delete comment?", function() {
                    var wish_place_id = $("#wish_place_id").text();
                    var comment_id = $delete_btn.parent().parent().find(".comment_id").text();
                    $.post({
                        url:'{% url "lets_travel_app:delete_comment_wish_place" %}',
                        data:{"comment_id": comment_id, "wish_place_id": wish_place_id},
                        success:function (response) {
                            if (response.success){
                                $delete_btn.parent().parent().parent().remove();
                                var comments_amount = response.amount_of_comments;
                                if (comments_amount ===  0 || comments_amount >= 2){
                                    $("#comments_amount").text(comments_amount + ' Comments');
                                }else{
                                    $("#comments_amount").text(comments_amount + ' Comment');
                                }
                            }else{
                                alert("error");
                            }
                        }

                    })
                });

            });


            $(".edit_comment_button").on("click", function(){
                $('.comment').each(function(){
                    var $edit_area_check = $(this).find(".edit_container");
                    if ($edit_area_check.css("display") === "block"){
                        $edit_area_check.css("display", "none");
                        var $exist_text_dev_check = $(this).find(".exist_text");
                        $exist_text_dev_check.css("display", "block");
                        var exist_text = $exist_text_dev_check.text();
                        $exist_text_dev_check.find(".exist_text").val(exist_text);
                    }
                });
                var $edit_comment_btn = $(this);
                var $exist_text_div = $edit_comment_btn.parent().parent().find(".exist_text");
                $exist_text_div.css("display", "none");
                var $edit_area = $edit_comment_btn.parent().parent().find(".edit_container");
                $edit_area.css("display", "block");
                var exist_text = $exist_text_div.text();
                $edit_area.find(".edit_text").val(exist_text);
            });


            $(".cancel_edit_comment").on("click", function(){
                var $cancel_edit_comment_btn = $(this);
                var $edit_area = $cancel_edit_comment_btn.parent().parent().find(".edit_container");
                $edit_area.css("display", "none");
                var $exist_text_div = $cancel_edit_comment_btn.parent().parent().find(".exist_text");
                $exist_text_div.css("display", "block");
            });


            $(".save_edited_comment").on("click", function(){
                var $save_edited_comment_btn = $(this);
                var comment_id = $save_edited_comment_btn.parent().parent().find(".comment_id").text();
                var $edit_comment_text = $save_edited_comment_btn.parent().parent().find(".edit_text");
                var edit_text = $edit_comment_text.val();
                $.post({
                    url:'{% url "lets_travel_app:edit_comment_wish_place" %}',
                    data:{"comment_id": comment_id, "edit_text": edit_text},
                    success:function (response) {
                        if (response.success){
                            var new_text = response.new_text;
                            var $edit_area = $save_edited_comment_btn.parent().parent().find(".edit_container");
                            $edit_area.css("display", "none");
                            var $exist_text_div = $save_edited_comment_btn.parent().parent().find(".exist_text");
                            $exist_text_div.css("display", "block");
                            $exist_text_div.val(new_text);
                            $exist_text_div.html(new_text)
                        }else{
                            alert("error");
                        }
                    }

                })
            });

        }


        $(document).ready(function(){
            init_buttons();
        });

    </script>

{% endblock %}